name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: j178/prek-action@v1

    - name: install clang-tools
      run: sudo apt install clang-tools -y

    - name: prek
      run: prek

  build-lib:
    runs-on: ubuntu-latest
    needs: prek
    steps:
    - uses: actions/checkout@v3

    - name: install nasm
      run: sudo apt install nasm -y

    - name: make
      run: make lib_asm

  tests:
    runs-on: ubuntu-latest
    needs: build-lib
    steps:
    - uses: actions/checkout@v3

    - name: install nasm
      run: sudo apt install nasm -y

    - name: make
      run: make test
